/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthLogoutRouteImport } from './routes/auth/logout'
import { Route as AuthLoginRouteImport } from './routes/auth/login'
import { Route as AuthCallbackRouteImport } from './routes/auth/callback'
import { Route as ApiSessionRouteImport } from './routes/api/session'
import { Route as ApiStripeWebhookRouteImport } from './routes/api/stripe/webhook'
import { Route as ApiRecipesHistoryRouteImport } from './routes/api/recipes/history'
import { Route as ApiRecipesGenerateRouteImport } from './routes/api/recipes/generate'
import { Route as ApiRecipesGenerationIdRouteImport } from './routes/api/recipes/$generationId'
import { Route as ApiBillingPortalRouteImport } from './routes/api/billing/portal'
import { Route as ApiBillingCheckoutRouteImport } from './routes/api/billing/checkout'
import { Route as ApiRecipesGenerationIdFavoriteRouteImport } from './routes/api/recipes/$generationId.favorite'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthLogoutRoute = AuthLogoutRouteImport.update({
  id: '/auth/logout',
  path: '/auth/logout',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/auth/login',
  path: '/auth/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthCallbackRoute = AuthCallbackRouteImport.update({
  id: '/auth/callback',
  path: '/auth/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSessionRoute = ApiSessionRouteImport.update({
  id: '/api/session',
  path: '/api/session',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiStripeWebhookRoute = ApiStripeWebhookRouteImport.update({
  id: '/api/stripe/webhook',
  path: '/api/stripe/webhook',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiRecipesHistoryRoute = ApiRecipesHistoryRouteImport.update({
  id: '/api/recipes/history',
  path: '/api/recipes/history',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiRecipesGenerateRoute = ApiRecipesGenerateRouteImport.update({
  id: '/api/recipes/generate',
  path: '/api/recipes/generate',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiRecipesGenerationIdRoute = ApiRecipesGenerationIdRouteImport.update({
  id: '/api/recipes/$generationId',
  path: '/api/recipes/$generationId',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiBillingPortalRoute = ApiBillingPortalRouteImport.update({
  id: '/api/billing/portal',
  path: '/api/billing/portal',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiBillingCheckoutRoute = ApiBillingCheckoutRouteImport.update({
  id: '/api/billing/checkout',
  path: '/api/billing/checkout',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiRecipesGenerationIdFavoriteRoute =
  ApiRecipesGenerationIdFavoriteRouteImport.update({
    id: '/favorite',
    path: '/favorite',
    getParentRoute: () => ApiRecipesGenerationIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/api/session': typeof ApiSessionRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/logout': typeof AuthLogoutRoute
  '/api/billing/checkout': typeof ApiBillingCheckoutRoute
  '/api/billing/portal': typeof ApiBillingPortalRoute
  '/api/recipes/$generationId': typeof ApiRecipesGenerationIdRouteWithChildren
  '/api/recipes/generate': typeof ApiRecipesGenerateRoute
  '/api/recipes/history': typeof ApiRecipesHistoryRoute
  '/api/stripe/webhook': typeof ApiStripeWebhookRoute
  '/api/recipes/$generationId/favorite': typeof ApiRecipesGenerationIdFavoriteRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/api/session': typeof ApiSessionRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/logout': typeof AuthLogoutRoute
  '/api/billing/checkout': typeof ApiBillingCheckoutRoute
  '/api/billing/portal': typeof ApiBillingPortalRoute
  '/api/recipes/$generationId': typeof ApiRecipesGenerationIdRouteWithChildren
  '/api/recipes/generate': typeof ApiRecipesGenerateRoute
  '/api/recipes/history': typeof ApiRecipesHistoryRoute
  '/api/stripe/webhook': typeof ApiStripeWebhookRoute
  '/api/recipes/$generationId/favorite': typeof ApiRecipesGenerationIdFavoriteRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/api/session': typeof ApiSessionRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/logout': typeof AuthLogoutRoute
  '/api/billing/checkout': typeof ApiBillingCheckoutRoute
  '/api/billing/portal': typeof ApiBillingPortalRoute
  '/api/recipes/$generationId': typeof ApiRecipesGenerationIdRouteWithChildren
  '/api/recipes/generate': typeof ApiRecipesGenerateRoute
  '/api/recipes/history': typeof ApiRecipesHistoryRoute
  '/api/stripe/webhook': typeof ApiStripeWebhookRoute
  '/api/recipes/$generationId/favorite': typeof ApiRecipesGenerationIdFavoriteRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/api/session'
    | '/auth/callback'
    | '/auth/login'
    | '/auth/logout'
    | '/api/billing/checkout'
    | '/api/billing/portal'
    | '/api/recipes/$generationId'
    | '/api/recipes/generate'
    | '/api/recipes/history'
    | '/api/stripe/webhook'
    | '/api/recipes/$generationId/favorite'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/api/session'
    | '/auth/callback'
    | '/auth/login'
    | '/auth/logout'
    | '/api/billing/checkout'
    | '/api/billing/portal'
    | '/api/recipes/$generationId'
    | '/api/recipes/generate'
    | '/api/recipes/history'
    | '/api/stripe/webhook'
    | '/api/recipes/$generationId/favorite'
  id:
    | '__root__'
    | '/'
    | '/api/session'
    | '/auth/callback'
    | '/auth/login'
    | '/auth/logout'
    | '/api/billing/checkout'
    | '/api/billing/portal'
    | '/api/recipes/$generationId'
    | '/api/recipes/generate'
    | '/api/recipes/history'
    | '/api/stripe/webhook'
    | '/api/recipes/$generationId/favorite'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ApiSessionRoute: typeof ApiSessionRoute
  AuthCallbackRoute: typeof AuthCallbackRoute
  AuthLoginRoute: typeof AuthLoginRoute
  AuthLogoutRoute: typeof AuthLogoutRoute
  ApiBillingCheckoutRoute: typeof ApiBillingCheckoutRoute
  ApiBillingPortalRoute: typeof ApiBillingPortalRoute
  ApiRecipesGenerationIdRoute: typeof ApiRecipesGenerationIdRouteWithChildren
  ApiRecipesGenerateRoute: typeof ApiRecipesGenerateRoute
  ApiRecipesHistoryRoute: typeof ApiRecipesHistoryRoute
  ApiStripeWebhookRoute: typeof ApiStripeWebhookRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/logout': {
      id: '/auth/logout'
      path: '/auth/logout'
      fullPath: '/auth/logout'
      preLoaderRoute: typeof AuthLogoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/login': {
      id: '/auth/login'
      path: '/auth/login'
      fullPath: '/auth/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/callback': {
      id: '/auth/callback'
      path: '/auth/callback'
      fullPath: '/auth/callback'
      preLoaderRoute: typeof AuthCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/session': {
      id: '/api/session'
      path: '/api/session'
      fullPath: '/api/session'
      preLoaderRoute: typeof ApiSessionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/stripe/webhook': {
      id: '/api/stripe/webhook'
      path: '/api/stripe/webhook'
      fullPath: '/api/stripe/webhook'
      preLoaderRoute: typeof ApiStripeWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/recipes/history': {
      id: '/api/recipes/history'
      path: '/api/recipes/history'
      fullPath: '/api/recipes/history'
      preLoaderRoute: typeof ApiRecipesHistoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/recipes/generate': {
      id: '/api/recipes/generate'
      path: '/api/recipes/generate'
      fullPath: '/api/recipes/generate'
      preLoaderRoute: typeof ApiRecipesGenerateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/recipes/$generationId': {
      id: '/api/recipes/$generationId'
      path: '/api/recipes/$generationId'
      fullPath: '/api/recipes/$generationId'
      preLoaderRoute: typeof ApiRecipesGenerationIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/billing/portal': {
      id: '/api/billing/portal'
      path: '/api/billing/portal'
      fullPath: '/api/billing/portal'
      preLoaderRoute: typeof ApiBillingPortalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/billing/checkout': {
      id: '/api/billing/checkout'
      path: '/api/billing/checkout'
      fullPath: '/api/billing/checkout'
      preLoaderRoute: typeof ApiBillingCheckoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/recipes/$generationId/favorite': {
      id: '/api/recipes/$generationId/favorite'
      path: '/favorite'
      fullPath: '/api/recipes/$generationId/favorite'
      preLoaderRoute: typeof ApiRecipesGenerationIdFavoriteRouteImport
      parentRoute: typeof ApiRecipesGenerationIdRoute
    }
  }
}

interface ApiRecipesGenerationIdRouteChildren {
  ApiRecipesGenerationIdFavoriteRoute: typeof ApiRecipesGenerationIdFavoriteRoute
}

const ApiRecipesGenerationIdRouteChildren: ApiRecipesGenerationIdRouteChildren =
  {
    ApiRecipesGenerationIdFavoriteRoute: ApiRecipesGenerationIdFavoriteRoute,
  }

const ApiRecipesGenerationIdRouteWithChildren =
  ApiRecipesGenerationIdRoute._addFileChildren(
    ApiRecipesGenerationIdRouteChildren,
  )

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ApiSessionRoute: ApiSessionRoute,
  AuthCallbackRoute: AuthCallbackRoute,
  AuthLoginRoute: AuthLoginRoute,
  AuthLogoutRoute: AuthLogoutRoute,
  ApiBillingCheckoutRoute: ApiBillingCheckoutRoute,
  ApiBillingPortalRoute: ApiBillingPortalRoute,
  ApiRecipesGenerationIdRoute: ApiRecipesGenerationIdRouteWithChildren,
  ApiRecipesGenerateRoute: ApiRecipesGenerateRoute,
  ApiRecipesHistoryRoute: ApiRecipesHistoryRoute,
  ApiStripeWebhookRoute: ApiStripeWebhookRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
